x-gotcha-env: &gotcha-env
  DATABASE_URL: postgres://gotcha:gotcha@postgres:5432/gotcha
  SECRET_KEY_BASE: ${SECRET_KEY_BASE:-f2a9de933f367f66dd076fc9ac579d078d807a1fb7ad1c3c9c6f8755b2374d8870770e43dcf0dcf5074873cc50efc8304a0e370555116ee21602d7244339c014}
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "true"
  GOTCHA_HOST: ${GOTCHA_HOST:-localhost}
  GOTCHA_USERNAME: ${GOTCHA_USERNAME:-}
  GOTCHA_PASSWORD: ${GOTCHA_PASSWORD:-}

services:
  web:
    image: ghcr.io/develonrails/gotcha:latest
    ports:
      - "${PORT:-80}:80"
    environment:
      <<: *gotcha-env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  worker:
    image: ghcr.io/develonrails/gotcha:latest
    command: bundle exec rails solid_queue:start
    environment:
      <<: *gotcha-env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:18
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: gotcha
      POSTGRES_PASSWORD: gotcha
      POSTGRES_DB: gotcha
    healthcheck:
      test: pg_isready -U gotcha
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres-data:
